<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FOCUS-QA-118" name="com.focus.testcases.OpeningStockTest" tests="109" failures="17" timestamp="22 Feb 2021 19:58:02 GMT" time="1697.555" errors="1">
  <testcase name="checkLoadingVoucherInformationFromCopyDocumentOnClickOnOk" time="20.241" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherWithRMAUnitsAndMandatoryMessageInThirdRow" time="14.355" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewEntryPageHeaderFields" time="5.355" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherByInputBinColumnManuallyInBinScreen" time="16.516" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherRmaWithZeroQuantity" time="5.967" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherBinWithManualInputQtyInBinPopForBinSplittingInThirdRow" time="27.788" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkTransactionMenuInInventoryMenu" time="6.956" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkInputingSerialNumbers" time="16.841" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewSaveDataWithoutExpiryDate" time="7.539" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewBinValuesForPreviousRowBinAfterAllocatingCurrentBinRow" time="20.741" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkOpeningStocksNewBinValuesForPreviousRowBinAfterAllocatingCurrentBinRow(OpeningStockTest.java:334)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkOpeningStocksNewBinValuesForPreviousRowBinAfterAllocatingCurrentBinRow -->
  <testcase name="checkOpeningStocksNewVoucherCreateViewOptionInHomePage" time="7.706" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewSaveInputRMAPopupScreen" time="11.135" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherCopyAndPasteThroughAllocateQtyInBinPage" time="10.018" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksNewVoucherAddingNewSerialNumbersOnRmaItemQtyUpdate" time="9.183" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksNewVoucherInputBinFifoBinPopupOptions" time="18.053" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherInputBatchAndBinPopupOptions" time="17.764" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkOpeningStocksNewVoucherInputBatchAndBinPopupOptions(OpeningStockTest.java:782)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkOpeningStocksNewVoucherInputBatchAndBinPopupOptions -->
  <testcase name="checkEditOpeningStocksNewVoucherBinAutoAllocationForBinSplittingInThirdRow" time="161.181" classname="com.focus.testcases.OpeningStockTest">
    <error type="org.openqa.selenium.TimeoutException" message="Expected condition failed: waiting for element to be clickable: Proxy element for: DefaultElementLocator &#039;By.xpath: //*[@id=&#039;id_transaction_entry_detail_table_body&#039;]/tr[4]/td[1]&#039; (tried for 20 second(s) with 1000 milliseconds interval)">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to be clickable: Proxy element for: DefaultElementLocator 'By.xpath: //*[@id='id_transaction_entry_detail_table_body']/tr[4]/td[1]' (tried for 20 second(s) with 1000 milliseconds interval)
	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:303)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:271)
	at com.focus.Pages.OpeningStockPage.checkEditOpeningStocksNewVoucherBinAutoAllocationForBinSplittingInThirdRow(OpeningStockPage.java:11375)
	at com.focus.testcases.OpeningStockTest.checkEditOpeningStocksNewVoucherBinAutoAllocationForBinSplittingInThirdRow(OpeningStockTest.java:640)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='id_transaction_entry_detail_table_body']/tr[4]/td[1]"}
  (Session info: chrome=88.0.4324.182)
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'FOCUS-QA-118', ip: '192.168.4.201', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.182, chrome: {chromedriverVersion: 87.0.4280.20 (c99e81631faa0..., userDataDir: C:\Users\admin\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:56792}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: f26fd230a3d73821a68d0ed2f08b9d58
*** Element info: {Using=xpath, value=//*[@id='id_transaction_entry_detail_table_body']/tr[4]/td[1]}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:317)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:419)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:309)
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy15.isDisplayed(Unknown Source)
	at org.openqa.selenium.support.ui.ExpectedConditions.elementIfVisible(ExpectedConditions.java:315)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$100(ExpectedConditions.java:44)
	at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:301)
	at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:298)
	at org.openqa.selenium.support.ui.ExpectedConditions$23.apply(ExpectedConditions.java:686)
	at org.openqa.selenium.support.ui.ExpectedConditions$23.apply(ExpectedConditions.java:682)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:248)
	... 26 more
]]>
    </error>
  </testcase> <!-- checkEditOpeningStocksNewVoucherBinAutoAllocationForBinSplittingInThirdRow -->
  <testcase name="checkAddButtonInRmaPageWithSelectingSerialNumbers" time="5.137" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewWareHouseOptions" time="6.198" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewSavedVoucherOnClickPreviousInEntryPage" time="20.852" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewUpdateVoucherOnClickPreviousInEntryPage" time="85.598" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkOpeningStocksNewUpdateVoucherOnClickPreviousInEntryPage(OpeningStockTest.java:767)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkOpeningStocksNewUpdateVoucherOnClickPreviousInEntryPage -->
  <testcase name="checkEditOpeningStocksNewVoucherBinWithManualInputQtyInBinPopForBinSplittingInThirdRow" time="12.082" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkEditOpeningStocksNewVoucherBinWithManualInputQtyInBinPopForBinSplittingInThirdRow(OpeningStockTest.java:647)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkEditOpeningStocksNewVoucherBinWithManualInputQtyInBinPopForBinSplittingInThirdRow -->
  <testcase name="checkOpeningStocksAddingDataInThirdRowForBinCheking" time="22.332" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherToDeleteOnClickOkButtonInAlertMessage" time="7.485" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewFirstRowCheckboxInCopyDocument" time="6.655" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherDateIsDisable" time="8.207" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksNewVoucherWithInputingAllocateQtyMoreThanAvailableQty" time="6.993" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksNewStockItemInFourthRow" time="12.954" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewEntryPageFooterFields" time="5.037" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewCopyDocumentScreenOptions" time="7.321" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherClickOnSuspendView" time="26.527" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewEditAndUpdateBatchNoWithoutExpiryDate" time="7.395" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkRMAPopupScreen" time="7.719" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkNewItemWithSameSerialNos" time="11.285" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkDeleteCreateViewOfHomePageOfOpeningStocksNew" time="20.625" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkInventoryMenu" time="7.564" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherBRItemInputBodyDataInFirstRow" time="12.381" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherSave" time="5.724" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewAddingStockItemInFourthRow" time="12.563" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherBinAutoAllocationForBinSplittingInThirdRow" time="9.892" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksNewAddingDataInFourthRowForBinCheking" time="18.457" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkEditOpeningStocksNewAddingDataInFourthRowForBinCheking(OpeningStockTest.java:589)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkEditOpeningStocksNewAddingDataInFourthRowForBinCheking -->
  <testcase name="checkOpeningStocksNewSaveWithoutMandatoryFields" time="6.382" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherBinsFifoInputWithoutBinSecondRow" time="9.742" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkSavingVoucherByChangingVoucherQuantitySerialNumbersSame" time="7.308" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherHomePageNewOptionOnClickDisplayEntryPage" time="8.700" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksNewVoucherByInputBinColumnManuallyInBinScreen" time="17.501" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkEditOpeningStocksNewVoucherByInputBinColumnManuallyInBinScreen(OpeningStockTest.java:596)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkEditOpeningStocksNewVoucherByInputBinColumnManuallyInBinScreen -->
  <testcase name="checkOpeningStocksNewSaveVoucherWithoutBatch" time="6.420" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksNewBinValuesForPreviousRowBinAfterAllocatingCurrentBinRow" time="31.317" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkEditOpeningStocksNewBinValuesForPreviousRowBinAfterAllocatingCurrentBinRow(OpeningStockTest.java:604)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkEditOpeningStocksNewBinValuesForPreviousRowBinAfterAllocatingCurrentBinRow -->
  <testcase name="checkOKButtonOnRevertChanges" time="5.641" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherRevertChangeOption" time="10.286" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOkButtonInRmaPageWithSelectionOfPartialSerialNumbers" time="7.197" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkOkButtonInRmaPageWithSelectionOfPartialSerialNumbers(OpeningStockTest.java:448)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkOkButtonInRmaPageWithSelectionOfPartialSerialNumbers -->
  <testcase name="checkOpeningStocksNewAddingDataInFourthRowForBinCheking" time="27.219" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherDisplayHomePage" time="26.923" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditAndUpdateBinBySelectingOtherBinThroughDoubleClickAndCheckBinColumnInVoucherOnClickOnOk" time="19.999" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkEditAndUpdateBinBySelectingOtherBinThroughDoubleClickAndCheckBinColumnInVoucherOnClickOnOk(OpeningStockTest.java:707)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkEditAndUpdateBinBySelectingOtherBinThroughDoubleClickAndCheckBinColumnInVoucherOnClickOnOk -->
  <testcase name="checkOpeningStocksNewCopyDocumentOption" time="6.585" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksNewVoucherRMAOkButtonOnRmaItemQtyUpdate" time="4.997" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherWithInputingAllocateQtyMoreThanAvailableQty" time="9.964" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksAddingBinInThridRowAutoAllocateInBin" time="16.711" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkEditOpeningStocksAddingBinInThridRowAutoAllocateInBin(OpeningStockTest.java:581)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkEditOpeningStocksAddingBinInThridRowAutoAllocateInBin -->
  <testcase name="checkSelectingBinThroughDoubleClickAndCheckBinColumnInVoucherOnClickOnOk" time="22.056" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherOnClickOnRevertChanges" time="17.221" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherBodyRowUnitsColumn" time="6.422" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditCreateViewOfHomePageOfOpeningStocksNew" time="33.604" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherOnClickCloseBtnInEntryPage" time="15.045" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherInputBinFifoBinPopupOptions" time="20.426" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksNewVoucherRMAPopUpOnRmaItemQtyUpdate" time="9.601" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksNewVoucherBinPopUpValuesAfterFullQtyConsumeinPreviousRows" time="22.959" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkEditOpeningStocksNewVoucherBinPopUpValuesAfterFullQtyConsumeinPreviousRows(OpeningStockTest.java:662)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkEditOpeningStocksNewVoucherBinPopUpValuesAfterFullQtyConsumeinPreviousRows -->
  <testcase name="checkEditVoucherSelectingBinThroughDoubleClickAndCheckBinColumnInVoucherOnClickOnOk" time="16.094" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkInputTheDuplicateSerialNumbersIsAllowingInRmaPage" time="14.618" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkClearButtonInRmaRowSerialNumberRmaPage" time="6.582" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherEntryPageRibbonControl" time="6.667" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksAddingDataInThirdRowForBinCheking" time="19.079" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkEditOpeningStocksAddingDataInThirdRowForBinCheking(OpeningStockTest.java:573)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkEditOpeningStocksAddingDataInThirdRowForBinCheking -->
  <testcase name="checkOpeningStocksNewVoucherBinPopUpValuesAfterFullQtyConsumeinPreviousRows" time="15.855" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkInputSerialNumbersIsAllowingGreaterThanInputVoucherQuantity" time="5.132" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewBodyRowsItemColumn" time="9.143" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewBinQuantityAfterAlocatingAndDeleting" time="19.272" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherEditByUpdatingBRCOGSAndNoBatchInFirstRow" time="7.409" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksNewVoucherConsumeFullCapacityInFifthRow" time="28.855" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkEditOpeningStocksNewVoucherConsumeFullCapacityInFifthRow(OpeningStockTest.java:654)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkEditOpeningStocksNewVoucherConsumeFullCapacityInFifthRow -->
  <testcase name="checkEditOpeningStocksNewDeleteRowBin" time="5.421" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksNewVoucherRMAItemQtyUpdate" time="6.000" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherWithInputingThroughAllocateQty" time="9.253" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksNewVoucherRMAClearButtonOnRmaItemQtyUpdate" time="5.080" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkSignInToCheckOpeningStocksVoucher" time="33.123" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewOkButtonRMAPopupScreenBatchBinAndRmaColumn" time="9.626" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherEditByUpdateExpiryDateInFirstRow" time="10.786" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkOpeningStocksNewVoucherEditByUpdateExpiryDateInFirstRow(OpeningStockTest.java:700)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkOpeningStocksNewVoucherEditByUpdateExpiryDateInFirstRow -->
  <testcase name="checkOpeningStocksNewSaveVoucherThroughCopyAndPasteFromVClipboardOnClickPreviousInEntryPage" time="17.004" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherAlertAndOKButtonInRevertChanges" time="7.477" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherDocumentNumber" time="5.768" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVouchersEntryPageNew" time="18.924" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherCopyAndPasteFromClipBoardOptions" time="19.743" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherCloseButtonInHomePage" time="19.359" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkCancelButtonInRmaPage" time="43.922" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewEntryPageBodyFields" time="9.258" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkClearButtonInRmaPage" time="5.240" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkRmaPageWithSelectingPartialSerialNumberLessThanInputedQtyInVoucher" time="10.670" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkRmaPageWithSelectingPartialSerialNumberLessThanInputedQtyInVoucher(OpeningStockTest.java:441)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkRmaPageWithSelectingPartialSerialNumberLessThanInputedQtyInVoucher -->
  <testcase name="checkSaveInCreateViewOfHomePageOfOpeningStocksNew" time="9.274" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherOnClickEditButtonInHomePage" time="27.152" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewDeleteRowBin" time="5.639" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksAddingBinInThridRowAutoAllocateInBin" time="15.509" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkStocksMenuInTransactionMenuInInventoryMenu" time="7.390" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksNewBinQuantityAfterAlocatingAndDeleting" time="22.783" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkEditOpeningStocksNewBinQuantityAfterAlocatingAndDeleting(OpeningStockTest.java:618)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkEditOpeningStocksNewBinQuantityAfterAlocatingAndDeleting -->
  <testcase name="checkEditOpeningStocksNewVoucherRMAAddButtonOnRmaItemQtyUpdate" time="5.101" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkSavingVoucherByCopyDocumentWithMandatoryCheck" time="25.311" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherSaveThroughCopyDocument" time="5.373" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkEditOpeningStocksNewVoucherWithInputingThroughAllocateQty" time="10.713" classname="com.focus.testcases.OpeningStockTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.OpeningStockTest.checkEditOpeningStocksNewVoucherWithInputingThroughAllocateQty(OpeningStockTest.java:633)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkEditOpeningStocksNewVoucherWithInputingThroughAllocateQty -->
  <testcase name="checkEditOpeningStocksNewVoucherBinsFifoInputWithoutBinSecondRow" time="10.184" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOKButtonInRmaPageWithoutSelectingSerialNumbers" time="7.174" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkInputingDifferentSerialNumbers" time="13.738" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkOpeningStocksNewVoucherConsumeFullCapacityInFifthRow" time="28.232" classname="com.focus.testcases.OpeningStockTest"/>
  <testcase name="checkSuspendOptionInOpeningStocks" time="24.074" classname="com.focus.testcases.OpeningStockTest"/>
</testsuite> <!-- com.focus.testcases.OpeningStockTest -->
